### ISSUE TITLE
**Suggestion** Make the token invalid if the user changes password

### ISSUE THREAD

**Issue by ASaa3d** [ammaralmorsi/eventbrite#26]
This is just a suggestion with low priority:

Scenario
1- Mobile(Android) user logged in using specific credentials (email , password) , recieved the token and saved it in local cache memory then closed the app.
2- Web(FrontEnd) user (using the same email) changed the password (from password to new_password).
3- Mobile user try to open the app and automatically login through the token he already have through verify-email api
4- the verify-email api should return error status code as the password changed and this token is old.

Implementation suggestion (2 ways)

1- add pass_last_updated param in all users in database and compare token_creation_date with this field in verify-email.
(this field is first initialized when user is created and updated whatever password is changed)

2- add the password to each token produced to be able to compare it with the actual password in database

Whatever method is followed you need to change the change-password api so it returns a new token when password is changed.

Again this is a suggestion and can be ignored but it solves a corner case.

**Comment by ASaa3d** [comment]
if the case is already handled in some other way please tell me

**Comment by ammaralmorsi** [comment]
this suggestion is implemented now but change, update, reset password will not return a new token, and any saved token will not be authorized so the subsequent requests will force the user to login again and get the new token.
