### ISSUE TITLE
Event related API's

### ISSUE THREAD

**Issue by h4z3m** [ammaralmorsi/eventbrite#28]
- [x] **auth/get-user:**
Description: Returns a user's first, last names and their avatar URL given their user ID.

Inputs:
```json
{
  "user_id": "string"
}
```
Outputs:
```json
{
"firstName": "string",
"lastName": "string",
"avatarURL": "string"
}
```

- [x] **events/get-likes:**

Description: Returns an array for the liked events' title, start time, location, and first ticket type by the user.
![image](https://user-images.githubusercontent.com/22566999/235257516-75ccd226-6ce6-4f3d-a7a2-8627b043136b.png)

Inputs:
```json
{
  "user_id": "string"
}
```
Outputs:
```json
{
"liked_events":[
  {
    "eventTitle":"string",
    "eventStartTime":"datetime",
    "eventLocation":"string",
    "firstTicketType":"string",
    "eventImageURL": "string"
  }
]
}
```

- [x] **events/get-following:**

Description: Returns an array for the users' first, last names & avatar URL that the user is following.
![image](https://user-images.githubusercontent.com/22566999/235257545-1cf910ed-8881-442b-b599-d1e1ec911548.png)

Inputs:
```json
{
  "user_id": "string"
}
```

Outputs:
```json
{
"following_creators": [
        {
            "firstName": "string",
            "lastName": "string",
            "avatarURL": "string"
        }
    ]
}
```

- [x] **auth/follow-user:**

Description: Adds a user to the following list of the current user.

Inputs:
```json
{
  "access_token":"string",
  "follow_user_id": "string"
}
```

Outputs (as you see fit):
```json
{
  "followed": "boolean"  
}
```

- [x] **auth/unfollow-user:**

Description: Removes a user from the following list of the current user.

Inputs:
```json
{
  "access_token":"string",
  "unfollow_user_id": "string"
}
```

Outputs (as you see fit):
```json
{
  "unfollowed": "boolean"  
}
```

- [x] **auth/like-event:**

Description: Adds an event to the liked events of the current user.

Inputs:
```json
{
  "access_token":"string",
  "liked_event_id": "string"
}
```

Outputs (as you see fit):
```json
{
  "liked": "boolean"  
}
```

- [x] **auth/unlike-event:**

Description: Removes an event from the liked events of the current user.

Inputs:
```json
{
  "access_token":"string",
  "unliked_event_id": "string"
}
```

Outputs (as you see fit):
```json
{
  "unliked": "boolean"
}
```

- [x] ~~events/get-tickets:~~

~~Description: Returns an array with the tickets for this event, each ticket has a name, price, sale end date, and a description.~~

- [x] ~~auth/make-order:~~

~~Description: Returns the order ID and total price for the purchase if successful given an array of ticket names and quantity to reserve.~~
![image](https://user-images.githubusercontent.com/22566999/235257155-23530f1e-e8e4-4800-99ff-a3321370ee49.png)

**Comment by h4z3m** [comment]
Please discard the last 2 tasks

**Comment by h4z3m** [comment]
Any user related function like auth/follow-user probably needs a new path as /auth is for authentication purposes only.

**Comment by ammaralmorsi** [comment]
- you will also need an api to add an event to the liked events??
      given user token and event_id -> add that event to the liked events
- for followed users, you requested an api to add a user to the followed users list
      given user token and user_id (user to be followed) -> add that user to the followed users
am i right?

**Comment by ASaa3d** [comment]
In the liked events can you please add the event image_url to be returned also as in the picture.

**Comment by h4z3m** [comment]
> - you will also need an api to add an event to the liked events??
> 
>       given user token and event_id -> add that event to the liked events
> 
> - for followed users, you requested an api to add a user to the followed users list
> 
>       given user token and user_id (user to be followed) -> add that user to the followed users
> 
> am i right?

- Yes, it shall be like-event as you described.
- Yes.

**Comment by ASaa3d** [comment]
> - you will also need an api to add an event to the liked events??
>       given user token and event_id -> add that event to the liked events
> - for followed users, you requested an api to add a user to the followed users list
>       given user token and user_id (user to be followed) -> add that user to the followed users
> am i right?


Also an api to unlike the event

**Comment by h4z3m** [comment]
@ahmedsaad562000 @ammaralmorsi 

Please revise the added APIs in the original issue post needed and the edit for returning the event image URL in the outputs as requested by @ahmedsaad562000 in **get-likes**.

For follow/like/unfollow/unlike APIs, I think you can choose the outputs as you see fit or what @ahmedsaad562000 may prefer, but I think no return for success with status 200 is better.

Sorry for the confusion, and thank you.

**Comment by ammaralmorsi** [comment]
auth/get_user is merged now but check the name

**Comment by ammaralmorsi** [comment]
for get-likes and get-following does the current deployed version satisfy you?
Or we should return the response as list of objects and not ids

**Comment by ammaralmorsi** [comment]
get following and get liked are now as requested by @ahmedsaad562000
