### ISSUE TITLE
Getting events 

### ISSUE THREAD

**Issue by yogilany** [ammaralmorsi/eventbrite#29]
### I will send a filter object in the parameters. filtration can be like this:

- Get online events only
- Get events given specific city
- Get events given a range of dates. Ex: from 20 Apr to 21 Apr 
- Get free events
- Get events given a word that can be in the title 

## NOTES

- **If the filter object is null, you get the events given the city only**
- **All retrieved events should be the public ones only**

**Comment by ASaa3d** [comment]
For the cross platform search

We need to add another parameter:

-Category

To be used for searching


Of course all theses parameter are intersecting ones

For example if i send more than filter 
The result should be the intersection of alll theses results

**Comment by ASaa3d** [comment]
Since this api will return a list of events objects 
we need the following data to be returned for each event object

Event name 
Event image
Event id
Event date
Event description

**Comment by ammaralmorsi** [comment]
the required api is now deployed but missing "free events" option, still working on tickets

**Comment by ammaralmorsi** [comment]
deployed

**Comment by ammaralmorsi** [comment]
with free filter added
