### ISSUE TITLE
Add Image Url To be used during login

### ISSUE THREAD

**Issue by ASaa3d** [ammaralmorsi/eventbrite#3]

**Comment by ASaa3d** [comment]
+ Add an Api that returns The imageUrl of a user by just using his email (used in a middle step in login logic)
API Description 
 Body Params : Email -> string
 response Body: ImageUrl -> string

**Comment by ammaralmorsi** [comment]
Working on it

**Comment by ammaralmorsi** [comment]
is the user verified? or this step will happen before verification?

**Comment by ASaa3d** [comment]
User is verified.

**Comment by ammaralmorsi** [comment]
done
