### ISSUE TITLE
Tickets and orders related APIs

### ISSUE THREAD

**Issue by yogilany** [ammaralmorsi/eventbrite#31]
## Ticket Class
- name
- type 
- **max quantity**
- **available quantity**
- price
- start date
- end date

## Promocode Class
- name
- limited to: (int) - if null then it's unlimited
- discount type: percentage/amount
- discount value: int

## Order Class
- id 
- first name (of the owner)
- last name
- email
- event id
- date of creation 
- price
- user_id

## Tickets (Attendees) class
- id 
- first name (of the attendee)
- last name
- email
- ticket type
- order id (null if the ticket is added manually)
- event id

## We need these queries 

1. Add ticket_type given the event_id
3. Add promo code given the event_id
4. Check promo code (return type and value if the promo code is found otherwise return null)
5. Reserve tickets until reservation is made (it should only decrement the count of available tickets)
6. Release tickets when the reservation session is canceled (it should only increment the count of available tickets)
7. Get event's tickets(attendees) of a specific event given event_id
8. Add a ticket(attendee) given event_id
9. Get orders of specific user given user_id
10. Get tickets(attendees) of a specific order (given order_id)
11. Get orders of a specific event given event_id

**Comment by ahmedsaad562000** [comment]
If applicable 
Promocode class can have 2 more attributes (not actually mentioned in the doc but they make sense)

1- expiration date (code can't be used after this data)

2- list of users (contains list of user ids that used this code so checking it will prevent the user from using the code more than 1 time)

**Comment by ASaa3d** [comment]
In the api #8
Get orders of specific user 

Can you please add the number of tickets in each order.

**Comment by ahmed1234552** [comment]
> In the api #8 Get orders of specific user
> 
> Can you please add the number of tickets in each order.

do you want to add number of tickets as attribute for order class? or you just need number of tickets as return of the api

**Comment by ahmed1234552** [comment]
> > In the api #8 Get orders of specific user
> > Can you please add the number of tickets in each order.
> 
> do you want to add number of tickets as attribute for order class? or you just need number of tickets as return of the api

or make other api to get the number of user tickets?

**Comment by ASaa3d** [comment]
> > In the api #8 Get orders of specific user
> > Can you please add the number of tickets in each order.
> 
> do you want to add number of tickets as attribute for order class? or you just need number of tickets as return of the api

yeah that would do

**Comment by ahmed1234552** [comment]
from 5 to 10 finished

**Comment by ASaa3d** [comment]
In api#8 can you add the event ImageURL of each order

For ui reaseons

**Comment by ASaa3d** [comment]
In api#8 can you add the event ImageURL of each order

For ui reaseons

**Comment by ahmed1234552** [comment]
I have added it to order class so you can use it..It will be at any "get" order api
