### ISSUE TITLE
EditUserInfo API

### ISSUE THREAD

**Issue by ASaa3d** [ammaralmorsi/eventbrite#4]
Add an Api that takes user token and user info to be changed 
Info that could be changed (firstname, lastname, imageUrl)
**Note: if any of the Body Params is null or empty then it should not be changed -> change only params that has values in it to be able to change only one of the params without changing the other params.  
API Description 
Params: UserToken
 Body Params : firstname -> string , lastname -> string , ImageUrl -> string
 response Body: any indicator that the user info updated successfully or not (response code only is sufficient).

**Comment by ammaralmorsi** [comment]
done

**Comment by ASaa3d** [comment]
I can't find this one in the documentation
