### ISSUE TITLE
modify /auth/login API to return firstName, lastName, and avatar

### ISSUE THREAD

**Issue by h4z3m** [ammaralmorsi/eventbrite#8]
It's required to return the first, last names and avatar in the response body after successful login authentication.

Modify the current API to be:

Request body:
```json
{
  "email": "string",
  "password": "string"
}
```
Successful response body:
```json
{
 "firstName":"string",
 "lastName":"string",
 "token":"string",
 "avatarURL":"string"
}
```

*Note: Failure response is unchanged.*

**Comment by ammaralmorsi** [comment]
merged
